// <auto-generated />
using System;
using HMS.Identity.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HMS.Identity.Api.Migrations
{
    [DbContext(typeof(AppIdentityDbContext))]
    partial class AppIdentityDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HMS.Identity.Infrastructure.Entities.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(96)
                        .HasColumnType("character varying(96)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(96)
                        .HasColumnType("character varying(96)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Permission")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("EmailAddress")
                        .IsUnique();

                    b.ToTable("employees", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("fe89d0c5-6232-421b-9926-05eff4433bd9"),
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EmailAddress = "admin@hms.local",
                            FirstName = "System",
                            IsActive = true,
                            LastName = "Administrator",
                            Password = "Admin@123",
                            Permission = "ALL",
                            Role = "ADMIN"
                        },
                        new
                        {
                            Id = new Guid("8f334882-8d97-4d54-a011-97d7c8c2a201"),
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EmailAddress = "doctor@hms.local",
                            FirstName = "Dawit",
                            IsActive = true,
                            LastName = "Doctor",
                            Password = "Admin@123",
                            Permission = "MANAGE_PATIENTS",
                            Role = "DOCTOR"
                        },
                        new
                        {
                            Id = new Guid("52f4d81d-e810-4c4e-895b-995f1bbf13a2"),
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EmailAddress = "receptionist@hms.local",
                            FirstName = "Hana",
                            IsActive = true,
                            LastName = "Reception",
                            Password = "Admin@123",
                            Permission = "REGISTER_PATIENTS",
                            Role = "RECEPTIONIST"
                        },
                        new
                        {
                            Id = new Guid("43a3b779-c6f9-496c-b8b6-81525947cf12"),
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EmailAddress = "nurse@hms.local",
                            FirstName = "Marta",
                            IsActive = true,
                            LastName = "Nurse",
                            Password = "Admin@123",
                            Permission = "ASSIST_DOCTORS",
                            Role = "NURSE"
                        },
                        new
                        {
                            Id = new Guid("83f36db8-5c4d-4f2a-9b54-00c31a31ab7d"),
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EmailAddress = "pharmacist@hms.local",
                            FirstName = "Selam",
                            IsActive = true,
                            LastName = "Pharmacist",
                            Password = "Admin@123",
                            Permission = "MANAGE_MEDICINES",
                            Role = "PHARMACIST"
                        },
                        new
                        {
                            Id = new Guid("7c5b23a5-5970-4b95-8d02-c36c1c9ac8e1"),
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EmailAddress = "lab@hms.local",
                            FirstName = "Abel",
                            IsActive = true,
                            LastName = "Lab",
                            Password = "Admin@123",
                            Permission = "CONDUCT_TESTS",
                            Role = "LAB_TECHNICIAN"
                        },
                        new
                        {
                            Id = new Guid("fbdd5447-1864-4420-b42d-60ba5afaf23e"),
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EmailAddress = "accountant@hms.local",
                            FirstName = "Mekdes",
                            IsActive = true,
                            LastName = "Accountant",
                            Password = "Admin@123",
                            Permission = "MANAGE_FINANCES",
                            Role = "ACCOUNTANT"
                        });
                });

            modelBuilder.Entity("HMS.Identity.Infrastructure.Entities.RolePermission", b =>
                {
                    b.Property<string>("Role")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PermissionsJson")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("permissions_json");

                    b.Property<int>("UserCount")
                        .HasColumnType("integer");

                    b.HasKey("Role");

                    b.ToTable("role_permissions", (string)null);

                    b.HasData(
                        new
                        {
                            Role = "ADMIN",
                            Description = "Full platform administration and configuration",
                            PermissionsJson = "[\"ALL\",\"MANAGE_USERS\",\"MANAGE_ROLES\",\"VIEW_REPORTS\"]",
                            UserCount = 0
                        },
                        new
                        {
                            Role = "DOCTOR",
                            Description = "Clinical care, diagnoses, prescriptions, and lab orders",
                            PermissionsJson = "[\"VIEW_PATIENTS\",\"MANAGE_CLINICAL\",\"ORDER_LABS\",\"PRESCRIBE\"]",
                            UserCount = 0
                        },
                        new
                        {
                            Role = "RECEPTIONIST",
                            Description = "Front desk registration and appointment scheduling",
                            PermissionsJson = "[\"REGISTER_PATIENTS\",\"BOOK_APPOINTMENTS\",\"VIEW_PATIENTS\"]",
                            UserCount = 0
                        },
                        new
                        {
                            Role = "NURSE",
                            Description = "Vitals capture and doctor assistance",
                            PermissionsJson = "[\"VIEW_PATIENTS\",\"CAPTURE_VITALS\",\"ASSIST_CLINICAL\"]",
                            UserCount = 0
                        },
                        new
                        {
                            Role = "PHARMACIST",
                            Description = "Medication review and dispensing",
                            PermissionsJson = "[\"VIEW_PRESCRIPTIONS\",\"DISPENSE_MEDICINE\"]",
                            UserCount = 0
                        },
                        new
                        {
                            Role = "LAB_TECHNICIAN",
                            Description = "Lab request processing and results workflow",
                            PermissionsJson = "[\"VIEW_LAB_REQUESTS\",\"UPDATE_LAB_STATUS\"]",
                            UserCount = 0
                        },
                        new
                        {
                            Role = "ACCOUNTANT",
                            Description = "Billing, invoices, and payment posting",
                            PermissionsJson = "[\"CREATE_INVOICES\",\"RECORD_PAYMENTS\",\"VIEW_FINANCE\"]",
                            UserCount = 0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
