// <auto-generated />
using System;
using HMS.Clinical.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HMS.Clinical.Api.Migrations
{
    [DbContext(typeof(AppClinicalDbContext))]
    partial class AppClinicalDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HMS.Clinical.Infrastructure.Entities.ClinicalEncounter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Assessment")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("ChiefComplaint")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DoctorId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid");

                    b.Property<string>("Plan")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("VisitType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.ToTable("clinical_encounters", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("7a58c9f1-4412-48dd-9165-7f08de63f863"),
                            Assessment = "Likely bacterial pharyngitis",
                            ChiefComplaint = "Fever and sore throat",
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DoctorId = new Guid("8f334882-8d97-4d54-a011-97d7c8c2a201"),
                            PatientId = new Guid("f64d3368-a4da-4d44-9612-5c302b0ec29a"),
                            Plan = "Antibiotics, hydration, follow-up in 5 days",
                            VisitType = "Outpatient"
                        });
                });

            modelBuilder.Entity("HMS.Clinical.Infrastructure.Entities.Diagnosis", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid>("DoctorId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("diagnoses", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("f4231a15-8a45-48cd-824a-28f454ccdfc1"),
                            Code = "J02.9",
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Acute pharyngitis",
                            DoctorId = new Guid("8f334882-8d97-4d54-a011-97d7c8c2a201"),
                            PatientId = new Guid("f64d3368-a4da-4d44-9612-5c302b0ec29a"),
                            Severity = "Moderate"
                        });
                });

            modelBuilder.Entity("HMS.Clinical.Infrastructure.Entities.LabRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DoctorId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("TestName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("lab_requests", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("3cb3eb61-03a4-4fec-8517-9d2778f6e40d"),
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DoctorId = new Guid("8f334882-8d97-4d54-a011-97d7c8c2a201"),
                            PatientId = new Guid("d5c6bf11-de68-4c3f-97d2-6d7fd12f8e80"),
                            Status = "Requested",
                            TestName = "Complete Blood Count"
                        });
                });

            modelBuilder.Entity("HMS.Clinical.Infrastructure.Entities.Prescription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DoctorId")
                        .HasColumnType("uuid");

                    b.Property<string>("Instructions")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("character varying(240)");

                    b.Property<string>("Medication")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("prescriptions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("325cf3a1-2af1-4b69-8a17-6fac5c547915"),
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DoctorId = new Guid("8f334882-8d97-4d54-a011-97d7c8c2a201"),
                            Instructions = "Take one capsule every 8 hours for 5 days",
                            Medication = "Amoxicillin 500mg",
                            PatientId = new Guid("f64d3368-a4da-4d44-9612-5c302b0ec29a")
                        });
                });

            modelBuilder.Entity("HMS.Clinical.Infrastructure.Entities.VitalSign", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BloodPressure")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("HeightCm")
                        .HasColumnType("decimal(6,2)");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid");

                    b.Property<int>("Pulse")
                        .HasColumnType("integer");

                    b.Property<int>("RespiratoryRate")
                        .HasColumnType("integer");

                    b.Property<decimal>("TemperatureC")
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("WeightKg")
                        .HasColumnType("decimal(6,2)");

                    b.HasKey("Id");

                    b.ToTable("vital_signs", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("a4d6c3ef-6d9f-4d35-9e92-40f980022f6a"),
                            BloodPressure = "118/76",
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            HeightCm = 164m,
                            PatientId = new Guid("f64d3368-a4da-4d44-9612-5c302b0ec29a"),
                            Pulse = 92,
                            RespiratoryRate = 18,
                            TemperatureC = 37.8m,
                            WeightKg = 62.5m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
